# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  max_anlagen:  10
  tiny_mce:
    my_settings:
      theme: advanced
      theme_advanced_buttons1 : "bold,italic,underline,separator,undo,redo,separator,cut,copy,paste"
      theme_advanced_buttons2 : ""
      theme_advanced_buttons3 : ""
